default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fbclone_development

test:
  <<: *default
  database: fbclone_test

production:
  <<: *default
  database: fbclone_production
  username: fbclone
  password: <%= ENV['FBCLONE_DATABASE_PASSWORD'] %>
